---
- name: Installation
  hosts: all
  become: True
  tasks:
    - name: add universe repository for bionic
      apt_repository: 
        repo: deb http://archive.ubuntu.com/ubuntu bionic universe
        state: present
      when: ansible_distribution_release == 'bionic'

#------------------------------------------------------------------------------------------------------#
#                                   BASIC SETUP AND INSTALLATION
#------------------------------------------------------------------------------------------------------#
    - name: Install a list of packages
      apt:
        name: "{{ packages }}"
      vars:
        packages:
        - locales
        - build-essential
        - python3-apt
        - python3-pip
        - htop
        - python3-setuptools
        - git
        - nginx
        state: forcereinstall

    - name: Install pip packages
      pip:
        name: "{{ packages }}"
      vars: 
        packages:
        - ansible
        - gunicorn
        - Fabric3
        - Flask
        - setuptools-rust

    - name: Upgrade pip
      pip: name=pip state=latest
      tags:
        - packages

    - name: Create directory ansible
      file:
        state: directory
        path: ansible

    - name: Pull project from github
      git:
        repo: 'https://github.com/KathurimaKimathi/Ansible-deploy.git'
        dest: kathurima/
        update: no
          
    